repos:
- repo: https://github.com/psf/black
  rev: 23.3.0
  hooks:
    - id: black
      args: ["--line-length=72"]
      language_version: python3.10

- repo: https://github.com/pycqa/isort
  rev: 5.12.0
  hooks:
    - id: isort
      args: ["--profile", "black", --line-length=72]

- repo: https://github.com/pycqa/flake8
  rev: 6.0.0
  hooks:
  - id: flake8
    args: ["--config=.flake8"]

- repo: https://github.com/hadialqattan/pycln
  rev: v2.1.3
  hooks:
  - id: pycln

- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v4.4.0
  hooks:
    - id: end-of-file-fixer
    - id: trailing-whitespace
    - id: detect-private-key
    - id: check-added-large-files
    - id: check-merge-conflict
    - id: check-json
    - id: check-yaml
